<?php declare(strict_types=1);

namespace EugeneErg\Graph\Collections;

use EugeneErg\Graph\ValueObjects\Arc;

class ArcCollection extends AbstractLineCollection
{
    protected const ELEMENT_CLASS = Arc::class;

    public function offsetSet($offset, $value): void
    {
        if ($this->count() === 13) {
            //throw new \Exception();
        }
        parent::offsetSet($offset, $value); // TODO: Change the autogenerated stub
    }
}
